TeProject/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from SleepApp.views import index,sleep
from FoodApp.views import calorie, food,fruit,vegetables,nuts,dairy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musics.urls', namespace='music')),
    path('sleep/',sleep,name='sleep'),
    path('chart/',index,name='index'),
    path('food/',food,name='food'),
    path('fruits/',fruit,name='fruits'),
    path('calorie/',calorie,name='calorie'),
    path('vegetables/',vegetables,name='vegetables'),
    path('nuts/',nuts,name='nuts'),
    path('dairy/',dairy,name='dairy')
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

musics/urls.py
from django import views
from musics.views import addMusic, homePage,main,physical,mental
from django.urls import path

app_name='musics'

urlpatterns = [
    path('',main,name="main"),
    path('physical/',physical,name='physical'),
    path('mental/',mental,name='mental'),
    path('home/',homePage,name='home_page'), 
    path('add/',addMusic,name='add_music'),  

]

FoodApp/models.py
from django.db import models

# Create your models here.

SleepApp/models.py
from datetime import time
from django.db import models


# Create your models here.
class Slee(models.Model):
    hours = models.IntegerField()

    DAYS_OF_WEEK = (
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    )
    days = models.CharField(max_length=20, choices=DAYS_OF_WEEK)

musics/models.py
from musics.helper import get_audio_length
from django.db import models
from .validators import validate_is_audio

class Music(models.Model):
    title=models.CharField(max_length=500)
    artiste=models.CharField(max_length=500)
    album=models.ForeignKey('Album',on_delete=models.SET_NULL,null=True,blank=True)
    time_length=models.DecimalField(max_digits=20, decimal_places=2,blank=True)
    audio_file=models.FileField(upload_to='musics/',validators=[validate_is_audio])
    cover_image=models.ImageField(upload_to='music_images/')

    def save(self,*args, **kwargs):
        if not self.time_length:
            # logic for getting length of audio
            audio_length=get_audio_length(self.audio_file)
            self.time_length =f'{audio_length:.2f}'

        return super().save(*args, **kwargs)

    class META:
        ordering="id"


class Album(models.Model):
    name=models.CharField(max_length=400)

SleepApp/forms.py
from django import forms
from matplotlib import widgets
from .models import Slee



DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
    ('Sunday', 'Sunday'),
)


class SleeForm(forms.Form):
    day = forms.CharField(
        label='Enter Day', widget=forms.Select(choices=DAYS_OF_WEEK))

FoodApp/views.py
from django.shortcuts import render

# Create your views here.
def food(request):
    return render(request,'food.html')
    
def fruit(request):
    return render(request,'fruits.html')
    
def calorie(request):
    return render(request,'calorie.html')

def vegetables(request):
    return render(request,'vegetables.html')

def nuts(request):
    return render(request,'nuts.html')

def dairy(request):
    return render(request,'dairy.html')

SleepApp/views.py
from datetime import timedelta, datetime
from django.shortcuts import render

from SleepApp.forms import SleeForm
from .models import Slee


def sleep(request):
    if request.GET.get("num1") and request.GET.get("num2"):
        num1 = request.GET.get("num1")
        num2 = request.GET.get("num2")

        num1 = datetime.strptime(num1, '%H:%M')

        num2 = datetime.strptime(num2, '%H:%M')

        if num2 < num1:
            nu = str(num1-num2)
            nu1 = nu.split(':')
            num = int(nu1[0])

        else:

            nu = str(num2-num1)
            nu1 = nu.split(':')

            num = int(nu1[0])

        print(num)
        print(type(num))

        day = request.GET.get("day")
        data = Slee(hours=num, days=day)
        data.save()
        fm = SleeForm()

        return render(request, "sleep.html", {"fm": fm, "msg": num})
    else:
        fm = SleeForm()
        return render(request, "sleep.html", {"fm": fm})


def index(request):
    labels = []
    data = []

    queryset = Slee.objects.all()

    for per in queryset:
        labels.append(per.days)
        data.append(per.hours)
    return render(request, 'chart.html', {
        'labels': labels,
        'data': data,
    })

musics/views.py
from musics.models import Album, Music
from django.shortcuts import redirect, render
from django.http import JsonResponse
from .form import AddMusicForm

def physical(request):
    return render(request,'physical.html')


def mental(request):
    return render(request, 'mental.html')


def main(request):
    return render(request,'main.html')

def homePage(request):
    musics=list(Music.objects.all().values())
    return render(request,'home.html',{
        'musics':musics
    })

def addMusic(request):
    form=AddMusicForm()

    if request.POST:
        form=AddMusicForm(request.POST,request.FILES)
     
        if form.is_valid():
            instance=form.save(commit=False)
            album=form.cleaned_data.get('album')
            if album:
                music_album=Album.objects.get_or_create(name=album)
                print(music_album)
                instance.album=music_album[0]
                instance.save()
                return redirect("music:home_page")
            else:
                instance.save()
                return redirect("music:home_page")

        else:
            print("no",form.data)
    
    return render(request,'addPage.html',{
        'form':form
    })

templates/addPage.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="text-center text-green-700 text-2xl font-bold mt-8 mb-10">Add A new Song</h2>
    <form action="" method="post" class="w-10/12 md:w-1/2 mx-auto mb-8" enctype="multipart/form-data">
   
  {% csrf_token %}

 
    <div class="my-4">
        <label for="id_title" class="text-lg ">Album (Optional):</label>
        <input type="text" name="album" maxlength="500" id="id_album" class="block w-full p-2 outline-none border-2 border-black rounded-lg">
    </div>
    <div class="my-4">
        <label for="id_title" class="text-lg ">Title:</label>
        <input type="text" name="title" maxlength="500" required="" id="id_title" class="block w-full p-2 outline-none border-2 border-black rounded-lg">
    </div>
    <div class="my-4">
        <label for="id_title" class="text-lg ">Artist:</label>
        <input type="text" name="artiste" maxlength="500" required="" id="id_artiste" class="block w-full p-2 outline-none border-2 border-black rounded-lg">
    </div>
    <div class=" overflow-hidden flex items-center justify-center flex-col my-4" >
        <div class="details-audio text-black text-base">

        </div>
        <div class="flex w-full items-center justify-center bg-grey-lighter">
        <label class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue-500 hover:text-white">
            <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
            </svg>
            <span class="mt-2 text-base leading-normal">Select a Music File</span>
            <input type='file' accept="audio/mp3" name="audio_file" class="hidden " onchange="showname('audio')" id="id_audio_file" required />
        </label> 
    </div>   
</div>

<div class=" overflow-hidden flex items-center justify-center flex-col my-4" >
    <div class="details-image text-black text-base">
        
    </div>
    <div class="flex w-full items-center justify-center bg-grey-lighter">
        <label class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue-500 hover:text-white">
            <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
            </svg>
            <span class="mt-2 text-base leading-normal">Select a Music Cover Image</span>
            <input type='file' accept="image/*" name="cover_image" class="hidden cover_image" onchange="showname('image')" id="id_cover_image" required />
            
        </label> 
        </div>      
    </div>
    <button class="bg-black p-4 text-white text-center ">
        Submit
    </button>
</form> 

<script>
    function showname (type) {
    if(type=='audio'){

        var name = document.getElementById('id_audio_file'); 
    }else{
        var name = document.getElementById('id_cover_image'); 

    }
    const file_name= name.files.item(0).name
    document.querySelector(`.details-${type}`).textContent=`${file_name}`
    };
</script>
{%endblock content%}

templates/base.html
{% load static %}
{% static "images" as imagePath %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>{% block Title %}Lively Healthcare Web application{% endblock Title %}</title>
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<link rel="stylesheet" href="https: //cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
			integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'css/styles.css' %}">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!--Chart js-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
			integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
			integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
		<!-- jQuery -->
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	</head>

	<body class='relative pt-8'>
		<nav class='p-4 bg-black bg-opacity-30 fixed top-0 left-0 w-full z-50'>
			<a href="{% url 'music:home_page' %}">
				<h2 class='text-white text-xl font-semibold'>
					<span class='text-green-800 font-black'>Lively </span> 
				</h2>
			</a>
		</nav>
{%block scripts%}
{%endblock scripts%}

		{% block content %}
		
		{% endblock content %}


	</body>

</html>

templates/calorie.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="styles.css" />
    <title>Food</title>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  </head>
  <body>
    <style>
      * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Roboto", sans-serif;
  }
  
  header {
    background-image: url("{% static 'images/cover.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
    height: 150px;
    position: relative;
  }
  
  .overlay {
    position: absolute;
    z-index: 1;
    top: 0;
    left: 0;
    height: 100%;
    right: 0;
    bottom: 0;
    padding: 0 !important;
    margin: 0 !important;
    background-color: rgba(10, 10, 10, 0.3);
  }
  
  nav {
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    z-index: 2;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    padding: 50px 60px 0 60px;
  }
  
  nav li {
    list-style: none;
    display: inline-block;
    padding-right: 10px;
    padding-left: 10px;
  }
  
  nav li span {
    padding-left: 5px;
  }
  
  li a {
    padding: 5px;
    background-color: #fff;
    text-decoration: none;
  }
  
  .calorie ion-icon {
    vertical-align: bottom;
    font-size: 20px;
    padding-right: 5px;
  }
  
  .calorie a {
    background-color: royalblue;
    color: #fff;
    cursor: pointer;
    text-decoration: none;
  }
  
  .container,
  .fruits-container {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    margin-top: 50px;
    padding-bottom: 100px;
  }
  
  .image {
    margin-right: 20px;
    margin-left: 20px;
    position: relative;
    overflow: hidden;
  }
  
  img {
    height: 100%;
    width: 100%;
    object-fit: contain;
    justify-items: flex-start;
  }
  
  .menu {
    height: 300px;
    width: 300px;
    align-content: flex-start;
    justify-items: flex-start;
  }
  
  .add-calorie {
    border: 10px;
  }
  
  /* ------------------------------ CART PAGE -------------------------- */
  
  .fruits-container {
    max-width: 650px;
    justify-content: space-around;
    margin: 0 auto;
    margin-top: 50px;
  
  }
  
  .fruits-container ion-icon{
      font-size: 25px;
      color: blue;
      margin-left: 10px;
      margin-right: 10px;
      cursor: pointer;
      display: flex;
      gap: 10px;
      margin-top: 10px;
      margin-bottom: 10px;

  }
  
  .fruit-header {
      width: 100%;
      max-width: 650px;
      display: flex;
      justify-content: flex-start;
      border-bottom: 4px solid lightgrey;
      margin: 0 auto;
  }
  
  .fruit-title{
      width: 45%;
  }
  
  .cal {
      width: 15%;
      border-bottom: 1px solid lightgrey;
      display: flex;
      align-items: center;
  }
  
  .quantity {
      width: 30%;
      border-bottom: 1px solid lightgray;
      display: flex;
      align-items: center;
  }
  
  .total {
      width: 10%;
      border-bottom: 1px solid lightgray;
      display: flex;
      align-items: center;
  }
  
  .fruit {
      width: 45%;
      display: flex;
      justify-content: space-around;
      align-items: center;
      padding: 10px 0;
      border-bottom: 1px solid lightgray;
  }
  
  .fruit ion-icon {
      cursor: pointer;
  }
  
  .fruits {
      width: 100%;
      display: flex;
      flex-wrap: wrap;
  }
  
  .fruits img {
      width: 75px;
  }
  
  .basketTotalContainer {
      display: flex;
      justify-content: flex-end;
      width: 100%;
      padding: 10px 0;
  }
  
  .basketTotalTitle {
      width: 30%;
  }
  
  .basketTotal {
      width: 10%;
  }

.caloriepage{
    gap: 5px;
    padding-left: 10px;
}

.calorie-container{
    display: flex;
    gap: 20px;
    flex-wrap: wrap;
}

.calorie-items{
    gap: 10px;
    padding-bottom: 5px;
}

#access ul {
    font-size: 13px;
    list-style: none;
    margin: 0 0 3px 0;;
    padding-left: 0;
}
#access {
    display: block;
    top: 100px;
    z-index: 9999;
}

#access li {
    position: relative;
    padding-left: 11px;
    margin-bottom: 15px;
}

.li-items{
    margin:0 0 10px 0
}


    </style>
    <header>
      <div class="overlay"></div>
      <nav>
        <h2>FOOD</h2>
        <ul>
          <li><a href="/food">Home</a></li>
          <!-- <li><a href="fruits.html">Fruits</a></li>
          <li><a href="vegetables.html">Vegetables</a></li> -->
          <li class="calorie">
            <a href="/calorie">
              <ion-icon name="basket"></ion-icon>Calorie<span>0</span>
            </a>
          </li>
        </ul>
      </nav>
    </header>

    <!-- <div>
            <ul>
                <li><a class="add-to-cart" href="#" data-name="Apple" data-price="1.22">Apple $1.22</a></li>
                <li><a class="add-to-cart" href="#" data-name="Banana" data-price="1.33">Banana $1.33</a></li>
                <li><a class="add-to-cart" href="#" data-name="Shoe" data-price="22.33">Shoe $22.33</a></li>
                <li><a class="add-to-cart" href="#" data-name="Frisbee" data-price="5.22">Frisbee $5.22</a></li>
            </ul>
            <button id="clear-cart">Clear</button>
        </div> -->

    <div class="fruits-container" id="access">
      <div class="fruit-header">
        <h5 class="fruit-title">ITEMS</h5>
        <h5 class="quantity">QUANTITY</h5>
        <h5 class="cal">CAL</h5>
        <h5 class="total">TOTAL</h5>
      </div>
      <div class="fruits-container">
        <ul class="calorie-items" id="show-cart">
          <li style="padding-left:1em">???????</li>
        </ul>
      </div>
      <div class="calorie-container">
        <div class="basketTotalContainer">You have <span id="count-cart"></span>   items in your cart</div>
        <div class="basketTotalContainer">Total Calorie: <span id="total-cart"></span> cal</div>
      </div>
    </div>

    <script src="{% static 'js/shoppingCart.js' %}"></script>

    <script>
      $(".add-to-cart").click(function (event) {
        event.preventDefault();
        var name = $(this).attr("data-name");
        var price = Number($(this).attr("data-price"));

        shoppingCart.addItemToCart(name, price, 1);
        displayCart();
      });

      $("#clear-cart").click(function (event) {
        shoppingCart.clearCart();
        displayCart();
      });

      function displayCart() {
        var cartArray = shoppingCart.listCart();
        console.log(cartArray);
        var output = "";

        for (var i in cartArray) {
          output +=
            "<li>" +
            cartArray[i].name +
            " <input class='item-count' type='number' data-name='" +
            cartArray[i].name +
            "' value='" +
            cartArray[i].count +
            "' >" +
            " x " +
            cartArray[i].price +
            " = " +
            cartArray[i].total +
            " <button class='plus-item' data-name='" +
            cartArray[i].name +
            "'>+</button>" +
            " <button class='subtract-item' data-name='" +
            cartArray[i].name +
            "'>-</button>" +
            " <button class='delete-item' data-name='" +
            cartArray[i].name +
            "'>X</button>" +
            "</li>";
        }

        $("#show-cart").html(output);
        $("#count-cart").html(shoppingCart.countCart());
        $("#total-cart").html(shoppingCart.totalCart());
      }

      $("#show-cart").on("click", ".delete-item", function (event) {
        var name = $(this).attr("data-name");
        shoppingCart.removeItemFromCartAll(name);
        displayCart();
      });

      $("#show-cart").on("click", ".subtract-item", function (event) {
        var name = $(this).attr("data-name");
        shoppingCart.removeItemFromCart(name);
        displayCart();
      });

      $("#show-cart").on("click", ".plus-item", function (event) {
        var name = $(this).attr("data-name");
        shoppingCart.addItemToCart(name, 0, 1);
        displayCart();
      });

      $("#show-cart").on("change", ".item-count", function (event) {
        var name = $(this).attr("data-name");
        var count = Number($(this).val());
        shoppingCart.setCountForItem(name, count);
        displayCart();
      });

      displayCart();
    </script>
  </body>
</html>

templates/chart.html
{% extends 'base.html' %}

{% block title %} Charts {% endblock %}

{%block scripts%}
<canvas id="myChart" width="200px" height="80px"></canvas>
<script>
    var d1 = {{ labels| safe}};
    var d2 = {{ data| safe}};
    const ctx = document.getElementById('myChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: d1,
            datasets: [{
                label: 'Hours of Sleep',
                data: d2,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {

            scales: {
                y: {
                    beginAtZero: true,

                }
            }
        }
    });
</script>


{%endblock scripts%}

{%block content%}
<div class="main">
    <a href="/sleep">
        <button type="button" class="btn btn-dark">Back </button>
    </a>
</div>


<!-- displaying the chart -->
<!-- you can also play around with the width and height to increase or decrease the chart size -->


{%endblock content%}

templates/main.html
{% extends 'base.html' %}
{% block title %} Main page {% endblock %}
{% block content %} 
<style>
    .main{
        padding: 200px;
        align-items: center;

    }
</style>
<div class="main" >
    <a href="/physical">
<button type="button" class="btn btn-dark">Physical </button>
    </a>

<a href="/mental">
<button type="button" class="btn btn-dark">Mental </button>
</a>

</div>





{% endblock %}

templates/mental.html
{% extends 'base.html' %}
{% block title %} Main page {% endblock %}
{% block content %}
<style>
    .main {
        padding: 200px;
        align-items: center;

    }
</style>
<div class="main">
    <a href="/home">
        <button type="button" class="btn btn-dark">Music</button>
    </a>

<a href="/sleep">
    <button type="button" class="btn btn-dark">Sleep Tracker</button>
</a>
</div>





{% endblock %}

templates/physical.html
{% extends 'base.html' %}
{% block title %} Main page {% endblock %}
{% block content %}
<style>
    .main {
        padding: 200px;
        align-items: center;

    }
</style>
<div class="main">
<a href="/physical">
    <button type="button" class="btn btn-dark">Workouts </button>
</a>

<a href="/food">
<button type="button" class="btn btn-dark">Food Calorie </button>
</a>

</div>

{% endblock %}

templates/sleep.html
{% extends 'base.html' %}

{% block title %} Charts {% endblock %}

{%block content%}
<style>
    *{
        background-color: #D4BBDD;
    }
.sleep{
    padding-left:300px;padding-top: 100px;
    align-items: center;

}.table1{
    background-color: #6A4973;
}
.heading1{
    
  text-decoration: underline overline;
  color: #6A4973;
  font-weight: bold;
  font-size: 28px;
  align-items: center;
 
}
</style>

<div class="sleep">
    <h1 class="heading1">
        ADD Time
    </h1>
    <br>
<form>
    <table border="2" class="table1">
        <label for="Sleep">Select a sleeping time:</label>
        <input type="time" id="num1" name="num1">
        <br>
        <br>

        <label for="Sleep">Select a waking time:</label>
        <input type="time" id="num2" name="num2" >
        <br>

        {{fm.as_table}}
    </table>
    <br>
    <br>
    <input type="submit" value="Calc" class="class="btn btn-dark">
    
    <br>
    <br>
</form>
{{ msg }}
{{ ms }}

<a href="/chart">
    <button type="button" class="btn btn-dark">Charts </button>
</a>

</div>


{%endblock content%}